# Browser types
windowrule = tag +firefox-based-browser, class:([fF]irefox|zen|librewolf)

# Only a subtle opacity change, but not for video sites
windowrule = opacity 1 0.97, tag:firefox-based-browser

# Some video sites should never have opacity applied to them
windowrule = opacity 1.0 1.0, initialTitle:((?i)(?:[a-z0-9-]+\.)*youtube\.com_/|app\.zoom\.us_/wc/home)
