alias lsx='eza -l --group-directories-first --icons=auto --time-style=default --no-user'
alias ls='lsx --no-permissions --no-filesize'
alias lsa='ls -a'
alias tree='eza --tree --level=2 --long --icons --git'
alias treea='tree -a'
