alias lsx='eza -lh --no-user --group-directories-first --icons=always --time-style=+"%Y-%m-%d %H:%M"'
alias ls='lsx --no-permissions --no-filesize'
alias lsa='ls -a'
alias treex='lsx --tree --level=2 --git'
alias tree='treex --no-permissions --no-filesize'
alias treea='treex -a'
